package initcmd

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/restarter/lets-workflow/cli/internal/envfile"
)

// orcaYAMLMarker is the first line of a LETS-managed orca.yaml. Without it the file
// is the team's own and is never rewritten.
const orcaYAMLMarker = "# lets:managed orca.yaml v1 - regenerated by lets init; remove this line to take ownership"

// orcaGUIPath prefixes the hook PATH: Orca is a GUI app, so its hooks may not see a
// login shell's PATH (where `lets` usually lives).
const orcaGUIPath = `PATH=\"$PATH:$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin\"`

// OrcaYAMLContent is the managed file. Orca reads orca.yaml from the main checkout
// (verified in Orca 1.4.203) and runs the hooks only after the user approves the file
// once in the Orca UI; both scripts end in a command that cannot fail the hook, and
// the SessionStart self-heal adopts a worktree whose setup hook did not run.
var OrcaYAMLContent = orcaYAMLMarker + "\n" +
	"scripts:\n" +
	"  setup: \"" + orcaGUIPath + "; command -v lets >/dev/null 2>&1 && lets worktree adopt --quiet || echo 'lets: adopt skipped - the session start will bootstrap'\"\n" +
	"  archive: \"" + orcaGUIPath + "; command -v lets >/dev/null 2>&1 && lets worktree release --quiet || true\"\n"

// EnsureOrcaYAML writes <root>/orca.yaml when the PROJECT .lets/.env selects the orca
// launcher (a personal ~/.lets/.env preference must not produce a committed team
// file). A foreign orca.yaml is never touched; a managed one is rewritten only when
// its content differs.
func EnsureOrcaYAML(root string) (Step, error) {
	proj, _ := readProjectEnv(root)
	if proj["LETS_LAUNCHER"] != "orca" {
		return Step{}, nil
	}
	path := filepath.Join(root, "orca.yaml")
	current, err := os.ReadFile(path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
	case err != nil:
		return Step{}, err
	case bytes.Equal(current, []byte(OrcaYAMLContent)):
		return Step{Status: StepSkip, Message: "orca.yaml (managed, in sync)"}, nil
	case !bytes.HasPrefix(current, []byte(orcaYAMLMarker)):
		return Step{Status: StepWarn, Message: "orca.yaml exists and is not LETS-managed - left untouched. To bootstrap Orca worktrees, add these hooks yourself:\n" + OrcaYAMLContent}, nil
	}
	if err := AtomicWriteBytes(path, []byte(OrcaYAMLContent), 0o644); err != nil {
		return Step{}, err
	}
	return Step{Status: StepOK, Message: "orca.yaml written (Orca runs `lets worktree adopt` / `release` from it) - commit it, and approve it once in Orca"}, nil
}

// readProjectEnv parses <root>/.lets/.env only (no user layer).
func readProjectEnv(root string) (map[string]string, error) {
	f, err := os.Open(filepath.Join(root, ".lets", ".env"))
	if err != nil {
		return map[string]string{}, err
	}
	defer func() { _ = f.Close() }()
	return envfile.Parse(f)
}
